### PR TITLE
Integrate `react-native-voice` into `expo-stt`

### PR DESCRIPTION
**Pull request by daheeahn**
- Currently, [anhtuank7c/expo-stt](https://github.com/anhtuank7c/expo-stt) has a separate Google voice recognition modal. Instead, I migrated the [react-native-voice](https://github.com/react-native-voice/voice) code onto this repository to use the built-in microphone like [react-native-voice](https://github.com/react-native-voice/voice).
- You can check the whole flow of voice recognition with [README](https://github.com/crossplatformkorea/expo-stt/blob/52d320d9a7ec6fa3ff7bafe41f9679926e290093/README.md)

### CODE REVIEW

**Comment by daheeahn** [comment]
I'll reflect review of GPT soon!!

**Comment by daheeahn** [comment]
Made minimal changes to maintain code consistency; no critical issues found

**Comment by hyochan** [comment]
Fixed below android build error on my side in [d51e53e](https://github.com/crossplatformkorea/expo-stt/pull/2/commits/d51e53ebd1bf92257ccd1a7ac35fc0e8f0741d3a)

```
e: file:///Users/hyo/Github/crossplatformkorea/expo-stt/android/src/main/java/expo/modules/stt/ExpoSttModule.kt:56:17 Type mismatch: inferred type is Boolean? but Boolean was expected
e: file:///Users/hyo/Github/crossplatformkorea/expo-stt/android/src/main/java/expo/modules/stt/ExpoSttModule.kt:86:13 Expected a value of type Any?
e: file:///Users/hyo/Github/crossplatformkorea/expo-stt/android/src/main/java/expo/modules/stt/ExpoSttModule.kt:94:13 Expected a value of type Any?
```

**Review by hyochan — CHANGES_REQUESTED** [review]
Nothing seems to happen when I press the `Recognize speech` button. Here are the logs I received:

```
 LOG  request permission null
 LOG  request permission null
 LOG  Check permission {"canAskAgain": true, "expires": "never", "granted": true, "status": "granted"}
```

Could you kindly share a screenshot of a working example? It would help me understand what the correct version should look like. Thank you!

**Review by hyochan — CHANGES_REQUESTED** [review]
https://github.com/crossplatformkorea/expo-stt/assets/27461460/bcf5ddbb-8bff-4f17-befe-c52a351a65c4

I am currently experiencing crashes on android device. Could you kindly check this?
If this is a permission issue, I think it'd be great to handle that in example either.

**Comment by hyochan** [comment]
Here is the logcat

```sh
2024-07-04 15:58:45.055 21312-21624 libc++abi               expo.modules.stt.example             E  terminating due to uncaught exception of type facebook::jsi::JSError: Cannot read property 'join' of undefined
                                                                                                    
                                                                                                    TypeError: Cannot read property 'join' of undefined
                                                                                                        at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=expo.modules.stt.example&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:1344:33)
2024-07-04 15:58:45.056 21312-21624 libc                    expo.modules.stt.example             A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 21624 (mqt_js), pid 21312 (les.stt.example)
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A  Cmdline: expo.modules.stt.example
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A  pid: 21312, tid: 21624, name: mqt_js  >>> expo.modules.stt.example <<<
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A  Abort message: 'terminating due to uncaught exception of type facebook::jsi::JSError: Cannot read property 'join' of undefined
                                                                                                    
                                                                                                    TypeError: Cannot read property 'join' of undefined
                                                                                                        at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=expo.modules.stt.example&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:1344:33)'
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A        #01 pc 000000000009dd84  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libc++_shared.so (BuildId: 982d68842b3bd6a164609be09a533324b1f28526)
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A        #02 pc 000000000009ca44  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libc++_shared.so (BuildId: 982d68842b3bd6a164609be09a533324b1f28526)
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A        #03 pc 000000000009ced4  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libc++_shared.so (BuildId: 982d68842b3bd6a164609be09a533324b1f28526)
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A        #04 pc 000000000009ce74  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libc++_shared.so (std::terminate()+56) (BuildId: 982d68842b3bd6a164609be09a533324b1f28526)
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A        #05 pc 00000000000ae3b8  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libexpo-modules-core.so (BuildId: 6ea46ab51ef214194a6936eeb060545af9c82efc)
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A        #06 pc 00000000000aeaa8  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libexpo-modules-core.so (expo::EventEmitter::Listeners::call(facebook::jsi::Runtime&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, facebook::jsi::Object const&, facebook::jsi::Value const*, unsigned long)+744) (BuildId: 6ea46ab51ef214194a6936eeb060545af9c82efc)
2024-07-04 15:58:45.910 21803-21803 DEBUG                   pid-21803                            A        #07 pc 00000000000b0128  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libexpo-modules-core.so (expo::EventEmitter::emitEvent(facebook::jsi::Runtime&, facebook::jsi::Object const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, facebook::jsi::Value const*, unsigned long)+216) (BuildId: 6ea46ab51ef214194a6936eeb060545af9c82efc)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #08 pc 00000000000ea874  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libexpo-modules-core.so (BuildId: 6ea46ab51ef214194a6936eeb060545af9c82efc)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #09 pc 00000000001f5d40  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #10 pc 00000000001f5c28  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (std::__ndk1::function<void ()>::operator()() const+20) (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #11 pc 000000000027d734  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #12 pc 000000000027d70c  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #13 pc 000000000027d6bc  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #14 pc 000000000027d690  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #15 pc 000000000027c724  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #16 pc 0000000000284abc  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #17 pc 00000000002830b0  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (std::__ndk1::function<void (facebook::jsi::Runtime&)>::operator()(facebook::jsi::Runtime&) const+28) (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #18 pc 0000000000287428  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #19 pc 00000000002873bc  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #20 pc 000000000028736c  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #21 pc 0000000000287340  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #22 pc 00000000002862c4  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #23 pc 0000000000284abc  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #24 pc 00000000002830b0  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (std::__ndk1::function<void (facebook::jsi::Runtime&)>::operator()(facebook::jsi::Runtime&) const+28) (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #25 pc 00000000002b2944  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #26 pc 00000000002b28bc  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #27 pc 00000000002b2868  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #28 pc 00000000002b283c  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #29 pc 00000000002b18b4  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #30 pc 00000000002d94dc  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #31 pc 00000000002d9440  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (std::__ndk1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const+44) (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #32 pc 00000000002d9400  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #33 pc 00000000002d9398  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #34 pc 00000000002d9350  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #35 pc 00000000002d932c  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #36 pc 00000000002d821c  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #37 pc 00000000001f5d40  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #38 pc 00000000001f5c28  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (std::__ndk1::function<void ()>::operator()() const+20) (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #39 pc 0000000000210934  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #40 pc 00000000002108cc  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #41 pc 0000000000210884  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #42 pc 0000000000210860  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #43 pc 000000000020f818  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libreactnativejni.so (BuildId: c47ef889b966436f)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #44 pc 0000000000019804  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libfbjni.so (facebook::jni::detail::MethodWrapper<void (facebook::jni::JNativeRunnable::*)(), &(facebook::jni::JNativeRunnable::run()), facebook::jni::JNativeRunnable, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>)+72) (BuildId: a22242831a7971267de570e06121acb588ce64cd)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #45 pc 0000000000019744  /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk!libfbjni.so (facebook::jni::detail::FunctionWrapper<void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>), facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*, void>::call(_JNIEnv*, _jobject*, void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>))+60) (BuildId: a22242831a7971267de570e06121acb588ce64cd)
2024-07-04 15:58:45.911 21803-21803 DEBUG                   pid-21803                            A        #50 pc 00000000002cb36c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk] (com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage+0)
2024-07-04 15:58:45.912 21803-21803 DEBUG                   pid-21803                            A        #59 pc 00000000002cb4fa  [anon:dalvik-classes.dex extracted in memory from /data/app/~~xyYMsU5MEi2bQe0GRqBIfQ==/expo.modules.stt.example-XAGLXqF1G4B-aLeo8Pe5dQ==/base.apk] (com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run+74)
```

**Review by hyochan — APPROVED** [review]

**Pull request merged**
